run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    check-shadowing: true
    enable-all: true
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/HakimIno/gool
  
  golint:
    min-confidence: 0.8
  
  misspell:
    locale: US
  
  gocyclo:
    min-complexity: 10
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocyclo
    - dupl
    - goconst
    - gosec
    - unconvert
    - prealloc
  
  disable:
    - deadcode
    - varcheck
    - structcheck

issues:
  exclude:
    - "G404: Use of weak random number generator"
  exclude-files:
    - ".*_test.go"
  max-issues-per-linter: 0
  max-same-issues: 0 